part of sudoku;

final hardPuzzle = [
  Input.cursor(column: 0, row: 4),
  Input.toggle(value: 7),
  Input.cursor(column: 0, row: 5),
  Input.toggle(value: 6),
  Input.cursor(column: 0, row: 8),
  Input.toggle(value: 3),
  Input.cursor(column: 1, row: 4),
  Input.toggle(value: 8),
  Input.cursor(column: 2, row: 0),
  Input.toggle(value: 7),
  Input.cursor(column: 2, row: 1),
  Input.toggle(value: 3),
  Input.cursor(column: 2, row: 7),
  Input.toggle(value: 1),
  Input.cursor(column: 3, row: 1),
  Input.toggle(value: 9),
  Input.cursor(column: 3, row: 2),
  Input.toggle(value: 2),
  Input.cursor(column: 3, row: 6),
  Input.toggle(value: 4),
  Input.cursor(column: 4, row: 2),
  Input.toggle(value: 7),
  Input.cursor(column: 4, row: 4),
  Input.toggle(value: 6),
  Input.cursor(column: 4, row: 5),
  Input.toggle(value: 8),
  Input.cursor(column: 5, row: 4),
  Input.toggle(value: 4),
  Input.cursor(column: 5, row: 7),
  Input.toggle(value: 7),
  Input.cursor(column: 7, row: 3),
  Input.toggle(value: 2),
  Input.cursor(column: 7, row: 4),
  Input.toggle(value: 5),
  Input.cursor(column: 7, row: 5),
  Input.toggle(value: 7),
  Input.cursor(column: 7, row: 6),
  Input.toggle(value: 3),
  Input.cursor(column: 7, row: 8),
  Input.toggle(value: 6),
  Input.cursor(column: 8, row: 0),
  Input.toggle(value: 4),
  Input.cursor(column: 8, row: 7),
  Input.toggle(value: 5),
  Input.cursor(column: 8, row: 8),
  Input.toggle(value: 8),
  Input.entryMode(EntryMode.value),
  Input.cursor(),
];

final expertPuzzle = [
  Input.cursor(column: 0, row: 4),
  Input.toggle(value: 4),
  Input.cursor(column: 0, row: 5),
  Input.toggle(value: 6),
  Input.cursor(column: 0, row: 6),
  Input.toggle(value: 5),
  Input.cursor(column: 1, row: 6),
  Input.toggle(value: 9),
  Input.cursor(column: 2, row: 2),
  Input.toggle(value: 6),
  Input.cursor(column: 2, row: 5),
  Input.toggle(value: 3),
  Input.cursor(column: 2, row: 7),
  Input.toggle(value: 2),
  Input.cursor(column: 3, row: 2),
  Input.toggle(value: 3),
  Input.cursor(column: 3, row: 4),
  Input.toggle(value: 8),
  Input.cursor(column: 4, row: 3),
  Input.toggle(value: 4),
  Input.cursor(column: 4, row: 5),
  Input.toggle(value: 9),
  Input.cursor(column: 4, row: 7),
  Input.toggle(value: 8),
  Input.cursor(column: 5, row: 1),
  Input.toggle(value: 9),
  Input.cursor(column: 5, row: 7),
  Input.toggle(value: 6),
  Input.cursor(column: 6, row: 0),
  Input.toggle(value: 7),
  Input.cursor(column: 6, row: 4),
  Input.toggle(value: 9),
  Input.cursor(column: 6, row: 8),
  Input.toggle(value: 5),
  Input.cursor(column: 7, row: 0),
  Input.toggle(value: 2),
  Input.cursor(column: 7, row: 1),
  Input.toggle(value: 4),
  Input.cursor(column: 7, row: 3),
  Input.toggle(value: 8),
  Input.cursor(column: 7, row: 4),
  Input.toggle(value: 1),
  Input.cursor(column: 8, row: 1),
  Input.toggle(value: 5),
  Input.cursor(column: 8, row: 4),
  Input.toggle(value: 3),
  Input.entryMode(EntryMode.value),
  Input.cursor(),
];

final evilPuzzle = [
  Input.cursor(column: 0, row: 1),
  Input.toggle(value: 8),
  Input.cursor(column: 0, row: 2),
  Input.toggle(value: 6),
  Input.cursor(column: 0, row: 4),
  Input.toggle(value: 1),
  Input.cursor(column: 0, row: 7),
  Input.toggle(value: 4),
  Input.cursor(column: 0, row: 8),
  Input.toggle(value: 7),
  Input.cursor(column: 1, row: 2),
  Input.toggle(value: 1),
  Input.cursor(column: 1, row: 3),
  Input.toggle(value: 5),
  Input.cursor(column: 2, row: 8),
  Input.toggle(value: 2),
  Input.cursor(column: 3, row: 1),
  Input.toggle(value: 6),
  Input.cursor(column: 3, row: 6),
  Input.toggle(value: 5),
  Input.cursor(column: 4, row: 4),
  Input.toggle(value: 4),
  Input.cursor(column: 4, row: 6),
  Input.toggle(value: 2),
  Input.cursor(column: 5, row: 0),
  Input.toggle(value: 7),
  Input.cursor(column: 5, row: 3),
  Input.toggle(value: 9),
  Input.cursor(column: 5, row: 7),
  Input.toggle(value: 6),
  Input.cursor(column: 5, row: 8),
  Input.toggle(value: 4),
  Input.cursor(column: 6, row: 1),
  Input.toggle(value: 7),
  Input.cursor(column: 6, row: 4),
  Input.toggle(value: 5),
  Input.cursor(column: 6, row: 7),
  Input.toggle(value: 8),
  Input.cursor(column: 6, row: 8),
  Input.toggle(value: 1),
  Input.cursor(column: 7, row: 6),
  Input.toggle(value: 6),
  Input.cursor(column: 8, row: 0),
  Input.toggle(value: 9),
  Input.cursor(column: 8, row: 5),
  Input.toggle(value: 3),
  Input.entryMode(EntryMode.value),
  Input.cursor(),
];
